# Generated by Django 5.1.15 on 2025-12-21 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('favorites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favoriteitem',
            name='favorites',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='favorites.favorites'),
        ),
        migrations.AddConstraint(
            model_name='favoriteitem',
            constraint=models.UniqueConstraint(fields=('favorites', 'product', 'accessory', 'supply'), name='unique_favorite_item'),
        ),
    ]
