# Generated by Django 5.2.4 on 2025-08-07 06:24

import apps.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('date', models.DateField(default=apps.utils.get_timenow)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'review',
                'ordering': ('-id',),
            },
        ),
    ]
