services:
  app:
    build:
      context: .
    volumes:
      - ./backend:/app
      - ./whoosh_index:/app/whoosh_index
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: on-failure
    command: >
      sh -c "python manage.py && python manage.py && python manage.py runserver 0.0.0.0:8000"

  redis:
    image: redis:alpine

  celery:
    build:
      context: .
    volumes:
      - ./backend:/app
    env_file:
      - .env
    restart: on-failure
    command: >
      sh -c "celery -A configs worker -l info"
