# Generated by Django 5.2.4 on 2025-08-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=255)),
                ('address_1', models.CharField(blank=True, max_length=100, null=True)),
                ('address_2', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('is_configuration', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'billing_details',
                'ordering': ('id',),
            },
        ),
    ]
