# Generated by Django 5.1.15 on 2025-12-21 19:29

import apps.users.managers
import core.services.photo_service
import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=50, unique=True, verbose_name='Enter your email')),
                ('avatar', models.ImageField(blank=True, upload_to=core.services.photo_service.PhotoService.upload_avatar)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('subscription_updates_news', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
                'ordering': ('id',),
            },
            managers=[
                ('objects', apps.users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^(?=.{2,25}$)[A-ZА-ЯЇІЄҐ][a-zа-яїієґ]*(?:-[A-ZА-ЯЇІЄҐ][a-zа-яїієґ]*)?$', 'Must start with a capital letter and contain only the letters')])),
                ('last_name', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^(?=.{2,25}$)[A-ZА-ЯЇІЄҐ][a-zа-яїієґ]*(?:-[A-ZА-ЯЇІЄҐ][a-zа-яїієґ]*)?$', 'Must start with a capital letter and contain only the letters')])),
                ('company_name', models.CharField(blank=True, max_length=25, null=True)),
                ('country', models.CharField(blank=True, max_length=25, null=True)),
                ('state', models.CharField(blank=True, max_length=25, null=True)),
                ('region', models.CharField(blank=True, max_length=25, null=True)),
                ('street_name', models.TextField(blank=True, max_length=30, null=True)),
                ('apartment_number', models.TextField(blank=True, max_length=30, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^(\\d{5}(-\\d{4})?|[A-Z]\\d[A-Z][ -]?\\d[A-Z]\\d|[A-Z]{1,2}\\d[A-Z\\d]?\\s?\\d[A-Z]{2})$', 'Zip code format must be as follows: 12345, 12345-6789, K1A 0B1, SW1A 1AA, 75008, 01001')])),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
                'ordering': ('id',),
            },
        ),
    ]
