# Generated by Django 5.2.4 on 2025-07-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='country',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
