# Generated by Django 5.1.15 on 2025-12-21 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_type', models.CharField(blank=True, choices=[('Soluble', 'Soluble'), ('Ground', 'Ground'), ('In grains', 'In grains'), ('In capsules', 'In capsules')], null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='products.product')),
            ],
            options={
                'db_table': 'supplies',
                'ordering': ('id',),
            },
        ),
    ]
