# Generated by Django 5.1.15 on 2025-12-21 19:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('processing', 'Order in processing'), ('preparing', 'Preparing'), ('shipping', 'Shipping'), ('in_transit', 'In transit'), ('delivered', 'Delivered')], default='processing', max_length=50)),
                ('ttn', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('billing_first_name', models.CharField(default='Smith', max_length=100)),
                ('billing_last_name', models.CharField(default='John', max_length=100)),
                ('billing_company_name', models.CharField(blank=True, default='Microsoft', max_length=255, null=True)),
                ('billing_country', models.CharField(default='Ukraine', max_length=100)),
                ('billing_state', models.CharField(blank=True, default='Odessa', max_length=100, null=True)),
                ('billing_region', models.CharField(blank=True, default='Odessa Region', max_length=100, null=True)),
                ('billing_street_name', models.CharField(blank=True, default='Champagne Lane', max_length=255, null=True)),
                ('billing_apartment_number', models.CharField(blank=True, default='7', max_length=50, null=True)),
                ('billing_zip_code', models.CharField(blank=True, default='65063', max_length=20, null=True)),
                ('billing_phone_number', models.CharField(default='380991112233', max_length=30)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='OrderPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'order_positions',
                'ordering': ('id',),
            },
        ),
    ]
