# Generated by Django 5.1.15 on 2025-12-21 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accessories', '0001_initial'),
        ('discount_codes', '0001_initial'),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='discount_codes.discountcode'),
        ),
        migrations.AddField(
            model_name='orderposition',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accessory_positions', to='accessories.accessory'),
        ),
        migrations.AddField(
            model_name='orderposition',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderposition',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_positions', to='products.product'),
        ),
        migrations.AddConstraint(
            model_name='orderposition',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', False), ('accessory__isnull', True)), models.Q(('product__isnull', True), ('accessory__isnull', False)), _connector='OR'), name='exactly_one_product_or_accessory'),
        ),
    ]
