# Generated by Django 5.1.15 on 2025-12-21 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billing_apartment_number',
            new_name='apartment_number',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='billing_company_name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='billing_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='billing_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='billing_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='billing_region',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='billing_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='billing_street_name',
            new_name='street_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='billing_zip_code',
            new_name='zip_code',
        ),
    ]
