# Generated by Django 5.1.15 on 2025-12-21 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_billing_apartment_number_order_apartment_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billing_phone_number',
            new_name='phone_number',
        ),
    ]
