# Generated by Django 5.1.15 on 2025-12-30 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderposition',
            name='total_price',
        ),
    ]
