# Generated by Django 5.1.15 on 2025-12-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_orderposition_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderposition',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
