# Generated by Django 5.2.4 on 2025-08-01 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_type', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='products.product')),
            ],
            options={
                'db_table': 'supply',
                'ordering': ('id',),
            },
        ),
    ]
