# Generated by Django 5.2.3 on 2025-06-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InitialTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('any_text', models.TextField(max_length=25)),
            ],
            options={
                'db_table': 'initial_test',
                'ordering': ['id'],
            },
        ),
    ]
