# Generated by Django 5.2.4 on 2025-07-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialtest',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='test_photo/'),
        ),
    ]
