# Generated by Django 5.1.15 on 2025-12-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('letter', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'services',
                'ordering': ('id',),
            },
        ),
    ]
