# Generated by Django 5.1.15 on 2026-02-10 19:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessoryphotosmodel',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
