# Generated by Django 5.2.4 on 2025-07-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('is_guest', models.BooleanField(default=True)),
                ('subscriptions', models.ManyToManyField(blank=True, related_name='customers', to='subscription.subscription')),
            ],
        ),
    ]
