# Generated by Django 5.2.4 on 2025-08-01 18:52

import django.db.models.deletion
from django.db import migrations, models

import apps.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlavorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'flavor_profile',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('brend', models.CharField(max_length=255)),
                ('caffeine_type', models.CharField(blank=True, max_length=25)),
                ('sort', models.CharField(blank=True, max_length=25)),
                ('roast', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('flavor_profiles', models.ManyToManyField(blank=True, related_name='products', to='products.flavorprofile')),
            ],
            options={
                'db_table': 'product',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default=apps.utils.get_timenow, max_length=255, null=True)),
                ('position', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='products.product')),
            ],
            options={
                'db_table': 'photo',
                'ordering': ('id',),
            },
        ),
    ]
