# Generated by Django 5.1.15 on 2025-12-21 19:29

import apps.utils
import core.services.photo_service
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accessories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlavorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'flavor_profile',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('caffeine_type', models.CharField(blank=True, choices=[('Caffeine', 'Caffeine'), ('Caffeine Medium', 'Caffeine Medium'), ('Decaffeinated', 'Decaffeinated')], max_length=18, null=True)),
                ('sort', models.CharField(blank=True, choices=[('Arabica', 'Arabica'), ('Robusta', 'Robusta'), ('Arabica/robusta blend', 'Arabica/robusta blend')], max_length=25, null=True)),
                ('roast', models.CharField(blank=True, choices=[('Light', 'Light'), ('Medium', 'Medium'), ('Dark', 'Dark')], max_length=13, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_special', models.BooleanField(default=False)),
                ('flavor_profiles', models.ManyToManyField(blank=True, related_name='products', to='products.flavorprofile')),
            ],
            options={
                'db_table': 'product',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default=apps.utils.get_timenow, max_length=255, null=True)),
                ('position', models.IntegerField(default=0)),
                ('accessory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos_url', to='accessories.accessory')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos_url', to='products.product')),
            ],
            options={
                'db_table': 'photo',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ProductPhotosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, upload_to=core.services.photo_service.PhotoService.upload_product_photo)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_photos', to='products.product')),
            ],
            options={
                'db_table': 'products_photo',
                'ordering': ('id',),
            },
        ),
    ]
